### ISSUE TITLE
E706: Variable type mismatch for: g:ctrlp_custom_ignore

### ISSUE THREAD

**Issue by vintikzzz** [kien/ctrlp.vim#162]
I've got this error while loading macvim. So ignoring don't work for me.

**Comment by jorgeas80** [comment]
Same silly mistake here. Thanks! :)

**Comment by pbassut** [comment]
Same thing!

**Comment by wsdjeg** [comment]
@pbassut  please use the active fork https://github.com/ctrlpvim/ctrlp.vim

**Comment by pbassut** [comment]
The issue regarding the wrong use of ctrlp_custom_ignore is in this repo. We can't move to the active fork in this case, can we?

**Comment by wsdjeg** [comment]
as the readme of this repo shows ,This project is unmaintained, You should use this [fork](https://github.com/ctrlpvim/ctrlp.vim) instead.
also you can have a look at my [vimrc](https://github.com/wsdjeg/DotFiles/blob/master/vimrc), ctrlp_custom_ignore works well
for the ctrlp,you can use these ways to add ignore;
1. g:ctrlp_custom_ignore
2. g:ctrlp_user_command
3.  set wildignore
but for git project ,if you have set your command to `git ls-files` these ways will not work,because git ls-filse only based on .gitignore,add it i will show the files you hava added to you repo ,the new file which has not been added  will not be shown
