### ISSUE TITLE
Not enough results

### ISSUE THREAD

**Issue by mateusz** [kien/ctrlp.vim#187]
10 results is not enough - I can't find a lot of my files because of name ambiguities. Can this be configurable somehow? Or at least make it possible to scroll up and down?

**Comment by yk2kus** [comment]
@ianmalott Thanks a lot. After trying many things only your solution worked!!

**Comment by ianmalott** [comment]
@yk2kus Glad it worked for you!

**Comment by marksweiss** [comment]
Just to add to @ianmalott's comment about balancing speed and window size. Please switch to using The Silver Searcher (ag) as your search tool -- it is lightning fast! The results window changes as you type, with zero lag. (It's also a great replacement for `grep` for code search, because it filters out everything you don't care about out of the box and is faster.) To switch, install Silver Searcher according to its instructions, and add this to your `.vimrc`: `let g:ctrlp_user_command = 'ag %s -l --nocolor -g <MY DEFAULT PATH>'`. So worth the few minutes this will take to set up!! Large `CTRLP` window plus `ag` is a great combination.

**Comment by butterywombat** [comment]
@marksweiss thank you so much for that! I already used ag but not with ctrlp. shit so fast now @_@
i went from a broken ctrl p to a working speedy one. hnnggg made my day

**Comment by marksweiss** [comment]
Awesome! That is such a great one. When your fingers get automatic with it it literally changes your whole workflow. Enjoy and glad to help!

**Comment by perkfly** [comment]
I'm using `let g:ctrlp_match_window = 'min:4,max:10,results=100'`

**Comment by lpy-neo** [comment]
@marksweiss thanks a lot
