### ISSUE TITLE
Is there a way to force CtrlP to only index text files?

### ISSUE THREAD

**Issue by techwizrd** [kien/ctrlp.vim#189]
CtrlP frequently shows image files, audio files, and binary files that Vim cannot edit and I'd like it to only show text files. Can this be done through the default options? Or should I write a plugin to filter mimetypes or something?

**Comment by lesterzone** [comment]
Interesting, I'll like to ignore `golang` binaries,
I'm using for development:

```
CompileDaemon -build="go build -o server" -directory="." -command="./server"
```

and it generates a `server` file, which I'll like to ignore since I'll like to `ctrl p server` and open `server.go`

Thanks for an amazing project

**Comment by xorbug** [comment]
Hi, was wondering if any mimetype filtering plugin existed for Vim to be used with CtrlP, and I found this (very old) issue. Now, I don't know if things have changed in the meantime, but no such plugin seems to exist. In any case, just for the sake of fun, along the lines of [this answer](https://askubuntu.com/a/522495) about mimetype searching, we can define a custom CtrlP command:
```vim
"only search for text files (by mime-type)
let s:find_exclude_paths     = '-not -path "*/\.git/*" '
let s:find_exclude_paths    .= '-not -path "*/venv/*" '                         
let s:find_exclude_paths    .= '-not -path "*/__pycache__/*" '
let g:ctrlp_user_command     =  "find %s -type f ". s:find_exclude_paths ." |         
            \ xargs -P0 -I{} mimetype {} |                                      
            \ awk -F': ' '{ if ($2 ~ /^text\\//) print $1 }'"
```
Note the exclude paths passed to `find`, since we cannot rely on `g:ctrlp_custom_ignore` when using `g:ctrlp_user_command` as per the doc, and `xargs -P0` for faster parallel processing. From some tests this may feel a bit slow depending on the directory size, and you may prefer to spend that time only once to blacklist file extensions as you encounter them (with `g:ctrlp_custom_ignore`) rather than waiting everytime for dynamic detection (should happen only once per session though, when the cache is populated), and to keep the things clean.

I din't play too much with it, as it was more like a proof of concept, and it may need some more tweakings but the result is fairly good and you can surely try this out and see if this is reasonable for your workflow, nonetheless.

Bye, and thanks to the authors and contributors for this tool!
