### ISSUE TITLE
Slow performance?

### ISSUE THREAD

**Issue by eproxus** [kien/ctrlp.vim#46]
Anyone else seeing quite bad performance? For example, `:CtrlPBuffer` takes up to 1 second before displaying anything on screen, even with relatively small buffer counts, like 3. I'd like this to be lightning fast, if possible...

**Comment by albasili** [comment]
I have a similar issue. CtrlP seems slow to accept keystroke when going through buffers and starting with a pristine vimrc did not help. My issue is only when I use `:CtrlpBuffer`. I have nearly 400 buffers open and it seems that it takes a while just to accept keystrokes, so I end up typing but nothing appears on the prompt. It renders the usage of the buffers just unfeasible. Funny thing is that I have more than few thousands entries in the project and using `:CtrlP` works faster (yes I'm caching results).

Not really sure why that happens. Any suggestion?

**Comment by alphaCTzo7G** [comment]
1. Use `wildignore` to ignore any folders you dont want `ctrlp` to look into or any files you want to ignore from the search. For example, people typically don't want to search through binary files
2. Use `ag` to speed up generation of file list
3. Use `ctrlp-py-matcher`: https://github.com/FelikZ/ctrlp-py-matcher. This uses a python engine rather than the default `viml` engine and can by itself give orders of magnitude faster result
4. use `git ls-files` to list the files instead of `vim's` globpath

You can find all the suggestions here: https://stackoverflow.com/questions/21346068/slow-performance-on-ctrlp-it-doesnt-work-to-ignore-some-folders
