### ISSUE TITLE
error indexing on windows

### ISSUE THREAD

**Issue by albfan** [kien/ctrlp.vim#612]
Just after pressing `ctrl+p` on a fresh install

>ERR: pcre_compile failed at position 19. Error: support for \P, \p, and \X has not been compiled
`prt  path  <mru>={ files }=<buf> <->`

but docs show windows is supported.

Is there any way to output info about the error? ctrlp debug mode?

**Comment by jmcomets** [comment]
I'm getting the same error on Windows after setting `let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden -g ""'`. Any updates on the issue? (I'd really like to use ag)

**Comment by chaseruppert** [comment]
I ran into the same problem with using ag with CtrlP on Windows. It turns out the command itself (I grabbed the same one from a website) is actually incorrect (at least, on Windows). If you run ag by itself:
ag [OPTIONS] PATTERN [PATH]

The options come first. So in the example above:
    let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden -g ""'

Should actually be (at least, on Windows):
    let g:ctrlp_user_command = 'ag -i --nocolor --nogroup --hidden -g "" %s'

I installed ag on Windows with Chocolatey, so maybe the command syntax is different for other platforms.

**Comment by albfan** [comment]
That works!

But for large codebases (here 7000+ files) becomes unusable.

**Comment by albfan** [comment]
A hack that can be usable:

les.cmd (stands for local search everything [es](http://www.voidtools.com/support/everything/command_line_interface/))  

    @echo off
    es %cd% !.git\ !.svn !target\ !build\ !bin\ %* | perl -pe "s/\%cd:\=\\\%\\\\//"

explain

- **es**: search tool from NTFS index
- !: exclude common project directories
- **%cd%**: current directory (see \ is escaped) 
- **perl -pe**: remove current directory from results (they are absolute)

so add to PATH and:

    let g:ctrlp_user_command = 'les %s'

will work really quick

**Comment by stargoo** [comment]
Thanks albfan! using Everything (es) was way faster than Ag on windows.
